Repository Clariteia/minos_microservice_networks, pull requests merged in 2021-05, with the labels that each got.

#96 #94 (update to `minos.common==0.0.5`)
  .idea/minos_microservice_networks.iml
  minos/networks/broker/abc.py
  minos/networks/broker/commands.py
  minos/networks/broker/dispatchers.py
  minos/networks/broker/events.py
  minos/networks/broker/services.py
  minos/networks/snapshots/dispatchers.py
  minos/networks/snapshots/services.py
  requirements_dev.txt
  tests/test_networks/test_broker/test_command.py
  tests/test_networks/test_broker/test_dispatcher.py
  tests/test_networks/test_broker/test_events.py
  tests/test_networks/test_broker/test_service.py
  tests/test_networks/test_snapshots/test_services.py
Labels: enhancement

#103 #89 (avoid reprocessing all `aggregate_event` entries each time maintaining an `offset`)
  minos/networks/snapshots/dispatchers.py
  tests/test_networks/test_snapshots/test_dispatchers.py
Labels: enhancement

#106 Issue 87 eventhandler refactor and tests
  minos/networks/__init__.py
  minos/networks/event.py
  minos/networks/event/__init__.py
  minos/networks/event/abc.py
  minos/networks/event/dispatcher.py
  minos/networks/event/event_server.py
  minos/networks/event/services.py
  tests/database_testcase.py
  tests/test_event_manager.py
  tests/test_networks/test_event/__init__.py
  tests/test_networks/test_event/test_dispatcher.py
  tests/test_networks/test_event/test_event_server.py
  tests/test_networks/test_event/test_event_services.py
Labels: enhancement

#102 #90 (snapshot config)
  .github/workflows/python-tests.yml
  minos/networks/snapshots/dispatchers.py
  requirements_dev.txt
  tests/test_config.yml
  tests/test_networks/test_snapshots/test_dispatchers.py
  tests/wrong_test_config.yml
Labels: enhancement

#108 #100 (remove `.idea` directory)
  .gitignore
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: bug

#120 Microservice REST
  minos/networks/__init__.py
  minos/networks/rest_interface/__init__.py
  minos/networks/rest_interface/handler.py
  minos/networks/rest_interface/service.py
  requirements_dev.txt
  tests/services/TestRestService.py
  tests/test_config.yml
  tests/test_networks/rest_interface/__init__.py
  tests/test_networks/rest_interface/test_interface.py
  tests/test_networks/rest_interface/test_service.py
Labels: enhancement

#136 #134 (flexible version contraints)
  pyproject.toml
Labels: bug

#140 #133 (handlers inherited from postgresql base class)
  minos/networks/handler/abc.py
  minos/networks/handler/command/services.py
  minos/networks/handler/command_reply/services.py
  minos/networks/handler/dispatcher.py
  minos/networks/handler/event/services.py
  minos/networks/handler/server.py
  tests/test_networks/test_handler/test_command/test_command_server.py
  tests/test_networks/test_handler/test_command/test_dispatcher.py
  tests/test_networks/test_handler/test_command_reply/test_command__reply_server.py
  tests/test_networks/test_handler/test_command_reply/test_dispatcher.py
  tests/test_networks/test_handler/test_event/test_dispatcher.py
  tests/test_networks/test_handler/test_event/test_event_server.py
Labels: miscellaneous

#142 Added storage to saga test configuration.
  poetry.lock
  tests/test_config.yml
Labels: miscellaneous

#144 #143 (update `minos.common`)
  minos/networks/__init__.py
  minos/networks/broker/__init__.py
  minos/networks/broker/abc.py
  minos/networks/broker/command_reply.py
  minos/networks/broker/commands.py
  minos/networks/broker/dispatchers.py
  minos/networks/broker/events.py
  minos/networks/handler/dispatcher.py
  minos/networks/handler/server.py
  minos/networks/snapshots/dispatchers.py
  poetry.lock
  pyproject.toml
  tests/test_networks/test_broker/test_command.py
  tests/test_networks/test_broker/test_command_reply.py
  tests/test_networks/test_broker/test_dispatcher.py
  tests/test_networks/test_broker/test_events.py
  tests/test_networks/test_broker/test_service.py
  tests/test_networks/test_handler/test_command/test_command_server.py
  tests/test_networks/test_handler/test_command/test_dispatcher.py
  tests/test_networks/test_handler/test_command_reply/test_command__reply_server.py
  tests/test_networks/test_handler/test_command_reply/test_dispatcher.py
  tests/test_networks/test_handler/test_event/test_dispatcher.py
  tests/test_networks/test_handler/test_event/test_event_server.py
  tests/test_networks/test_snapshots/test_dispatchers.py
  tests/test_networks/test_snapshots/test_services.py
Labels: miscellaneous

#152 #151 (fix `aiokafka.AIOKafkaConsumer.stop`)
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/command_replies/services.py
  minos/networks/handlers/commands/services.py
  minos/networks/handlers/events/services.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_services.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_services.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_services.py
  tests/utils.py
Labels: bug

#148 #110 #145 (Integrate `CommandReplyHandler` with `SagaManager` and Integrate `CommandHandler` with `CommandReplyBroker` )
  minos/networks/handlers/__init__.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/entries.py
  minos/networks/handlers/events/handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/utils.py
Labels: enhancement

#155 #151 (kafka consumer stop revisit)
  minos/networks/handlers/abc/consumers.py
Labels: bug

#154 #153 (sphinx)
  Makefile
  docs/authors.rst
  docs/conf.py
  docs/history.rst
  docs/index.rst
  docs/modules.rst
  docs/readme.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#156 #151 (kafka consumer stop revisit)
  minos/networks/handlers/abc/consumers.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/utils.py
Labels: bug

#164 #163 (Assume that `MinosSagaManager.run` is asynchronous)
  minos/networks/handlers/command_replies/handlers.py
  tests/utils.py
Labels: enhancement

#162 #160 (optional arguments broker setup)
  minos/networks/brokers/command_replies.py
  minos/networks/brokers/commands.py
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_brokers/test_commands.py
  tests/test_networks/test_brokers/test_events.py
Labels: bug

#170 ISSUE #161 and #169
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/events/handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
Labels: enhancement

#172 Handlers > dont send self.TABLE as parameter to super class #168
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/abc/setups.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/events/consumers.py
  minos/networks/handlers/events/handlers.py
Labels: enhancement

#173 Directly pass the **kwargs to the service dispatchers
  minos/networks/brokers/services.py
  minos/networks/handlers/command_replies/services.py
  minos/networks/handlers/commands/services.py
  minos/networks/handlers/events/services.py
  minos/networks/snapshots/services.py
Labels: enhancement

#178 Extend RestBuilder from MinosSetup
  minos/networks/rest/builders.py
  minos/networks/rest/services.py
  tests/test_networks/test_rest/test_builders.py
Labels: enhancement

#176 #175 (Temporally remove the kafka consumer groups)
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/events/consumers.py
Labels: bug

#180 Inject minos.common.Config into the minos.networks.RestBuilder endpoints
  minos/networks/rest/builders.py
  tests/services/TestRestService.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_services.py
Labels: enhancement

#183 Add Reply on CommandReplyBroker instead of CommandHandler
  minos/networks/brokers/command_replies.py
  minos/networks/handlers/commands/handlers.py
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
Labels: enhancement

#182 #181 (Start using `minos.common.CommandReply`)
  minos/networks/handlers/commands/handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/utils.py
Labels: enhancement

#186 #171 (Simplify `minos.networks.Consumer` constructor)
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/events/consumers.py
Labels: enhancement

#189 Update minos-microservice-common to the latest version
  minos/networks/brokers/command_replies.py
  minos/networks/brokers/commands.py
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/commands/handlers.py
  poetry.lock
  tests/test_config.yml
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_brokers/test_commands.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/utils.py
Labels: enhancement

#188 Issue #184 documentation
  AUTHORS.md
  CONTRIBUTING.md
  HISTORY.md
  Makefile
  README.md
  RUNTHETESTS.md
  SETUP.md
  docs/Makefile
  docs/conf.py
  docs/history.rst
  docs/index.rst
  docs/readme.rst
  docs/runthetests.rst
  docs/usage.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#194 #193 (Fix bug related with kafka consumer config)
  minos/networks/brokers/producers.py
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/events/consumers.py
Labels: bug
