Repository Clariteia/minos_microservice_networks, pull requests merged in 2021-09, with the labels that each got.

#367 #366 - hotfixes
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/dynamic/handlers.py
  minos/networks/handlers/dynamic/pools.py
  minos/networks/snapshots.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
Labels: bug

#370 #369 - Add support for `__get_enroute__`
  minos/networks/decorators/analyzers.py
  minos/networks/decorators/builders.py
  minos/networks/discovery/connectors.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/consumers.py
  minos/networks/handlers/events/handlers.py
  minos/networks/rest/handlers.py
  tests/test_networks/test_decorators/test_analyzers.py
  tests/utils.py
Labels: enhancement

#381 #373 - Update tests to be compatible with latest `minos-microservice-common` version
  poetry.lock
  tests/test_config.yml
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/utils.py
Labels: enhancement

#384 #383 (update `minos-microservice-common`)
  minos/networks/snapshots.py
  poetry.lock
  pyproject.toml
  tests/test_config.yml
  tests/test_networks/test_snapshots.py
  tests/utils.py
Labels: enhancement

#388 #380 - Stop using `NoReturn` arbitrarily
  minos/networks/brokers/abc.py
  minos/networks/decorators/definitions/abc.py
  minos/networks/discovery/clients.py
  minos/networks/discovery/connectors.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/abc/setups.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/consumers.py
  minos/networks/handlers/events/handlers.py
  minos/networks/rest/handlers.py
  tests/test_networks/test_brokers/test_abc.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/utils.py
Labels: enhancement

#387 #386 - Use timezone dates in messaging queues
  minos/networks/brokers/abc.py
  minos/networks/brokers/producers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/abc/setups.py
  minos/networks/handlers/consumers.py
  minos/networks/handlers/dynamic/handlers.py
  minos/networks/handlers/entries.py
  tests/test_networks/test_brokers/test_abc.py
  tests/test_networks/test_brokers/test_producers.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_consumers.py
  tests/test_networks/test_handlers/test_dynamic/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/utils.py
Labels: enhancement

#375 #374 - Kong client
  minos/networks/__init__.py
  minos/networks/discovery/__init__.py
  minos/networks/discovery/clients/__init__.py
  minos/networks/discovery/clients/abc.py
  minos/networks/discovery/clients/kong.py
  minos/networks/discovery/clients/minos.py
  minos/networks/discovery/connectors.py
  minos/networks/exceptions.py
  poetry.lock
  tests/docker-compose.yml
  tests/test_config.yml
  tests/test_networks/test_discovery/test_clients/test_kong.py
  tests/test_networks/test_discovery/test_clients/test_minos_discovery.py
  tests/test_networks/test_discovery/test_connectors.py
Labels: enhancement

#391 #390 - Use `import_module` on `discovery.client` loading from config
  minos/networks/discovery/connectors.py
  tests/test_config.yml
  tests/test_networks/test_discovery/test_connectors.py
Labels: miscellaneous

#395 #394 - Fix bugs related with dependency injections
  minos/networks/brokers/producers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/dynamic/pools.py
  minos/networks/handlers/services.py
  minos/networks/snapshots.py
Labels: bug

#396 #393 - Support multiple event handling functions for same topic
  minos/networks/decorators/analyzers.py
  minos/networks/handlers/consumers.py
  minos/networks/handlers/events/handlers.py
  tests/services/commands.py
  tests/services/queries.py
  tests/test_config.yml
  tests/test_networks/test_decorators/test_analyzers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement
