Repository Clariteia/minos_microservice_networks, pull requests merged in 2021-07, with the labels that each got.

#239 #232 (Improve `minos.networks.HttpRequest`)
  minos/networks/handlers/commands/messages.py
  minos/networks/rest/messages.py
  poetry.lock
  pyproject.toml
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_messages.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_messages.py
Labels: enhancement

#243 #242 (`Command.reply_topic` must be always included)
  minos/networks/__init__.py
  minos/networks/brokers/command_replies.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/rest/__init__.py
  minos/networks/rest/builders.py
  minos/networks/rest/messages.py
  poetry.lock
  pyproject.toml
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_brokers/test_commands.py
  tests/test_networks/test_brokers/test_events.py
  tests/test_networks/test_brokers/test_producers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_rest/test_builders.py
Labels: enhancement

#244 #241 (Integrate `CommandResponseException` into `CommandHandler` workflow)
  minos/networks/__init__.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/commands/__init__.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/commands/messages.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/utils.py
Labels: enhancement

#245 #229 (Add database-level lock to avoid table creation issues)
  minos/networks/brokers/abc.py
  minos/networks/handlers/abc/setups.py
Labels: bug

#248 #247 (Update `minos-microservice-common`)
  minos/networks/brokers/abc.py
  minos/networks/brokers/command_replies.py
  minos/networks/brokers/commands.py
  minos/networks/brokers/events.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/commands/messages.py
  minos/networks/rest/builders.py
  poetry.lock
  pyproject.toml
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_brokers/test_commands.py
  tests/test_networks/test_brokers/test_events.py
  tests/test_networks/test_brokers/test_producers.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_messages.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_messages.py
  tests/utils.py
Labels: enhancement

#257 Simplify postgres config on Github Actions
  .github/workflows/python-tests.yml
  .gitignore
Labels: enhancement

#255 #254 (subscribe command reply to event's reply topics)
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/entries.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement

#260 Modify minos.networks.EventHandler.dispatch_one
  minos/networks/handlers/events/handlers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement

#263 Define subscribe decorator
  minos/networks/__init__.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/decorators.py
  tests/test_networks/test_handlers/test_decorators.py
Labels: enhancement

#272 #269 (Add `minos.networks.DynamicHandler`)
  minos/networks/__init__.py
  minos/networks/exceptions.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/dynamic/__init__.py
  minos/networks/handlers/dynamic/handlers.py
  poetry.lock
  pyproject.toml
  tests/test_config.yml
  tests/test_networks/test_handlers/test_dynamic/__init__.py
  tests/test_networks/test_handlers/test_dynamic/test_handlers.py
Labels: enhancement

#267 Define Enroute decorator
  minos/networks/__init__.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/decorators.py
  tests/test_networks/test_handlers/test_decorators.py
Labels: enhancement

#289 #266 (Fix bug related with the ip address extraction)
  minos/networks/__init__.py
  minos/networks/discovery/connectors.py
  minos/networks/utils.py
  tests/test_networks/test_discovery/test_connectors.py
Labels: bug

#292 #290 integrate call handlers
  minos/networks/__init__.py
  minos/networks/exceptions.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/decorators.py
  minos/networks/handlers/decorators/__init__.py
  minos/networks/handlers/decorators/analyzers.py
  minos/networks/handlers/decorators/api.py
  minos/networks/handlers/decorators/builders.py
  minos/networks/handlers/decorators/definitions/__init__.py
  minos/networks/handlers/decorators/definitions/abc.py
  minos/networks/handlers/decorators/definitions/broker.py
  minos/networks/handlers/decorators/definitions/kinds.py
  minos/networks/handlers/decorators/definitions/rest.py
  minos/networks/handlers/events/consumers.py
  minos/networks/handlers/events/handlers.py
  minos/networks/rest/builders.py
  tests/services/CommandTestService.py
  tests/services/CqrsTestService.py
  tests/services/DecoratedService.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_decorators.py
  tests/test_networks/test_handlers/test_decorators/__init__.py
  tests/test_networks/test_handlers/test_decorators/test_analyzers.py
  tests/test_networks/test_handlers/test_decorators/test_api.py
  tests/test_networks/test_handlers/test_decorators/test_builders.py
  tests/test_networks/test_handlers/test_decorators/test_definitions/__init__.py
  tests/test_networks/test_handlers/test_decorators/test_definitions/test_abc.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_services.py
  tests/utils.py
Labels: enhancement

#293 Integrate @enroute decorator and v0.1.6 of minos-microservice-common lib
  minos/networks/__init__.py
  minos/networks/exceptions.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/decorators.py
  minos/networks/handlers/decorators/__init__.py
  minos/networks/handlers/decorators/analyzers.py
  minos/networks/handlers/decorators/api.py
  minos/networks/handlers/decorators/builders.py
  minos/networks/handlers/decorators/definitions/__init__.py
  minos/networks/handlers/decorators/definitions/abc.py
  minos/networks/handlers/decorators/definitions/broker.py
  minos/networks/handlers/decorators/definitions/kinds.py
  minos/networks/handlers/decorators/definitions/rest.py
  minos/networks/handlers/events/consumers.py
  minos/networks/handlers/events/handlers.py
  minos/networks/rest/builders.py
  poetry.lock
  pyproject.toml
  tests/services/CommandTestService.py
  tests/services/CqrsTestService.py
  tests/services/TestRestService.py
  tests/services/commands.py
  tests/services/queries.py
  tests/services/sagas.py
  tests/test_config.yml
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_decorators.py
  tests/test_networks/test_handlers/test_decorators/__init__.py
  tests/test_networks/test_handlers/test_decorators/test_analyzers.py
  tests/test_networks/test_handlers/test_decorators/test_api.py
  tests/test_networks/test_handlers/test_decorators/test_builders.py
  tests/test_networks/test_handlers/test_decorators/test_definitions/__init__.py
  tests/test_networks/test_handlers/test_decorators/test_definitions/test_abc.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_services.py
  tests/utils.py
  tests/wrong_test_config.yml
Labels: enhancement

#287 #284 (create reply handler pool)
  .github/workflows/python-tests.yml
  minos/networks/__init__.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/dynamic/__init__.py
  minos/networks/handlers/dynamic/handlers.py
  minos/networks/handlers/dynamic/pools.py
  tests/docker-compose.yml
  tests/test_networks/test_handlers/test_dynamic/test_handlers.py
  tests/test_networks/test_handlers/test_dynamic/test_pools.py
Labels: enhancement

#297 #296 (migrate `minos.common.messages` to `minos.networks.messages`)
  minos/networks/__init__.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/commands/messages.py
  minos/networks/handlers/decorators/builders.py
  minos/networks/handlers/decorators/definitions/abc.py
  minos/networks/messages.py
  minos/networks/rest/builders.py
  minos/networks/rest/messages.py
  tests/services/commands.py
  tests/services/queries.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_decorators/test_builders.py
  tests/test_networks/test_handlers/test_decorators/test_definitions/test_abc.py
  tests/test_networks/test_messages.py
  tests/test_networks/test_rest/test_builders.py
  tests/utils.py
Labels: enhancement

#301 #299 (Rename `minos.networks.CommandRequest` as `minos.networks.HandlerRequest`)
  minos/networks/__init__.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/commands/__init__.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/commands/messages.py
  minos/networks/handlers/messages.py
  tests/services/commands.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_messages.py
Labels: enhancement

#303 #302 (Rename `HttpRequest` as `RestRequest`)
  minos/networks/__init__.py
  minos/networks/rest/__init__.py
  minos/networks/rest/builders.py
  minos/networks/rest/messages.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_messages.py
Labels: enhancement

#306 #298 (Implement `minos.networks.WrappedRequest`)
  minos/networks/__init__.py
  minos/networks/decorators/builders.py
  minos/networks/messages.py
  tests/test_networks/test_decorators/test_builders.py
  tests/test_networks/test_messages.py
  tests/utils.py
Labels: enhancement

#307 #305 (Now `EventHandler` have a `(request: Request) -> NoReturn` prototype)
  minos/networks/handlers/events/handlers.py
  tests/services/queries.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement

#313 Bug with socket.getfqdn()
  minos/networks/utils.py
Labels: bug, enhancement

#314 #311 (Send start event on `ConsumerService` classes)
  minos/networks/handlers/command_replies/services.py
  minos/networks/handlers/commands/services.py
  minos/networks/handlers/events/services.py
Labels: bug

#315 #308 (Remove method implemented with the same behaviour by the parent class)
  minos/networks/handlers/dynamic/pools.py
Labels: enhancement

#316 Update to latest minos_microservice_common lib and modify config
  .github/workflows/python-tests.yml
  minos/networks/brokers/command_replies.py
  minos/networks/brokers/commands.py
  minos/networks/brokers/events.py
  minos/networks/brokers/producers.py
  minos/networks/discovery/connectors.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/dynamic/handlers.py
  minos/networks/handlers/dynamic/pools.py
  minos/networks/handlers/events/consumers.py
  minos/networks/handlers/events/handlers.py
  minos/networks/rest/builders.py
  poetry.lock
  pyproject.toml
  tests/test_config.yml
  tests/test_networks/test_brokers/test_abc.py
  tests/test_networks/test_brokers/test_producers.py
  tests/test_networks/test_handlers/test_abc/test_consumers.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_abc/test_setups.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_dynamic/test_handlers.py
  tests/test_networks/test_handlers/test_dynamic/test_pools.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/wrong_test_config.yml
Labels: enhancement

#321 #318 (Enrich type hints of `EnrouteDecorator` function)
  minos/networks/decorators/definitions/abc.py
Labels: enhancement
