Repository Clariteia/minos_microservice_networks, pull requests merged in 2021-06, with the labels that each got.

#196 Add retry column to Handlers
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/abc/setups.py
  minos/networks/handlers/entries.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement

#205 #203 plain functions as controllers
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/commands/handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement

#202 #200 (`Request` and `Response` implementations)
  minos/networks/__init__.py
  minos/networks/handlers/__init__.py
  minos/networks/handlers/commands/__init__.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/commands/messages.py
  minos/networks/rest/__init__.py
  minos/networks/rest/builders.py
  minos/networks/rest/messages.py
  poetry.lock
  tests/services/CommandTestService.py
  tests/services/TestRestService.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_messages.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_messages.py
Labels: enhancement

#197 Concurrent *queue table reads
  minos/networks/handlers/abc/handlers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement

#206 Broker Producer queue lock
  minos/networks/brokers/producers.py
  tests/test_networks/test_brokers/test_producers.py
Labels: enhancement

#210 Retry logic make one more attempt than necessary
  minos/networks/brokers/producers.py
  minos/networks/handlers/abc/handlers.py
Labels: bug

#211 Refactor SQL builders - issue #199
  minos/networks/brokers/abc.py
  minos/networks/brokers/producers.py
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/abc/setups.py
  tests/test_config.yml
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_brokers/test_commands.py
  tests/test_networks/test_brokers/test_events.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: refactor

#216 #215 (Simplify tests using `minos.common.MinosModel` instances as much as possible)
  tests/aggregate_classes.py
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_brokers/test_commands.py
  tests/test_networks/test_brokers/test_events.py
  tests/test_networks/test_brokers/test_producers.py
  tests/test_networks/test_exceptions.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_messages.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
  tests/test_networks/test_rest/test_messages.py
  tests/test_networks/test_snapshots/test_builders.py
  tests/test_networks/test_snapshots/test_entries.py
  tests/utils.py
Labels: miscellaneous

#217 #212 (move snapshot logic to common)
  minos/networks/__init__.py
  minos/networks/exceptions.py
  minos/networks/snapshots.py
  minos/networks/snapshots/__init__.py
  minos/networks/snapshots/builders.py
  minos/networks/snapshots/entries.py
  poetry.lock
  pyproject.toml
  tests/test_networks/test_exceptions.py
  tests/test_networks/test_snapshots.py
  tests/test_networks/test_snapshots/__init__.py
  tests/test_networks/test_snapshots/test_builders.py
  tests/test_networks/test_snapshots/test_entries.py
  tests/utils.py
Labels: enhancement

#227 Created `docker-compose` for testing - issue #226
  tests/docker-compose.yml
Labels: enhancement

#228 Discovery subscriber - issue #221
  minos/networks/__init__.py
  minos/networks/discovery/__init__.py
  minos/networks/discovery/clients.py
  minos/networks/discovery/connectors.py
  tests/test_config.yml
  tests/test_networks/test_discovery/__init__.py
  tests/test_networks/test_discovery/test_clients.py
  tests/test_networks/test_discovery/test_connectors.py
Labels: enhancement

#223 #222 (lazy dispatcher initialisation by `aiomisc` services)
  minos/networks/__init__.py
  minos/networks/brokers/services.py
  minos/networks/discovery/__init__.py
  minos/networks/discovery/clients.py
  minos/networks/discovery/connectors.py
  minos/networks/handlers/command_replies/services.py
  minos/networks/handlers/commands/services.py
  minos/networks/handlers/events/services.py
  minos/networks/rest/builders.py
  minos/networks/rest/services.py
  minos/networks/snapshots.py
  tests/test_config.yml
  tests/test_networks/test_brokers/test_services.py
  tests/test_networks/test_discovery/__init__.py
  tests/test_networks/test_discovery/test_clients.py
  tests/test_networks/test_discovery/test_connectors.py
  tests/test_networks/test_snapshots.py
Labels: bug

#231 #230 (Fix bug related with unclosed connection to discovery)
  minos/networks/__init__.py
  minos/networks/discovery/clients.py
  minos/networks/exceptions.py
  tests/test_networks/test_discovery/test_clients.py
Labels: bug

#235 #208 (Simplify tests)
  minos/networks/__init__.py
  minos/networks/brokers/__init__.py
  minos/networks/brokers/abc.py
  minos/networks/brokers/command_replies.py
  minos/networks/brokers/commands.py
  minos/networks/brokers/events.py
  minos/networks/exceptions.py
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/consumers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/consumers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/events/consumers.py
  minos/networks/handlers/events/handlers.py
  tests/test_networks/test_brokers/test_abc.py
  tests/test_networks/test_brokers/test_command_replies.py
  tests/test_networks/test_brokers/test_commands.py
  tests/test_networks/test_brokers/test_events.py
  tests/test_networks/test_brokers/test_producers.py
  tests/test_networks/test_discovery/test_connectors.py
  tests/test_networks/test_handlers/test_abc/__init__.py
  tests/test_networks/test_handlers/test_abc/test_consumers.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_handlers/test_abc/test_setups.py
  tests/test_networks/test_handlers/test_command_replies/test_consumers.py
  tests/test_networks/test_handlers/test_command_replies/test_handlers.py
  tests/test_networks/test_handlers/test_commands/test_consumers.py
  tests/test_networks/test_handlers/test_commands/test_handlers.py
  tests/test_networks/test_handlers/test_events/test_consumers.py
  tests/test_networks/test_handlers/test_events/test_handlers.py
Labels: enhancement

#236 #234 (Increase handlers logging)
  minos/networks/brokers/command_replies.py
  minos/networks/brokers/commands.py
  minos/networks/brokers/events.py
  minos/networks/brokers/producers.py
  minos/networks/discovery/clients.py
  minos/networks/discovery/connectors.py
  minos/networks/handlers/abc/consumers.py
  minos/networks/handlers/abc/handlers.py
  minos/networks/handlers/command_replies/handlers.py
  minos/networks/handlers/commands/handlers.py
  minos/networks/handlers/events/handlers.py
  minos/networks/rest/builders.py
  tests/test_networks/test_handlers/test_abc/test_handlers.py
  tests/test_networks/test_rest/test_builders.py
  tests/test_networks/test_rest/test_messages.py
Labels: enhancement

#237 #233 (handle discovery connector exceptions)
  minos/networks/discovery/clients.py
  tests/test_networks/test_discovery/test_clients.py
Labels: enhancement
